// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Call(arg1, arg2) {
  return window['go']['main']['App']['Call'](arg1, arg2);
}

export function TranslateBatch() {
  return window['go']['main']['App']['TranslateBatch']();
}
